### ISSUE TITLE
Wiggle request buffering

### ISSUE THREAD

**Issue by marprok** [tsoding/wiggle#19]
When the server is down, every wiggle request that happens will be lost. For example, if a subscription/donation event is related to a wiggle request, then this request will never happen and it might upset the donator. So I think that the requests should be buffered just to cover this case.

**Comment by rexim** [comment]
@marprok I don't see a way to implement that in the scope of this project. If the server is down there is simply no place to buffer the request. Such buffering should happen at the chat bot side.

**Comment by marprok** [comment]
@rexim Well, in this case I guess the issue is not relevant here but maybe sometime in the future you want to implement it in the chat bot side as you said.

**Comment by rexim** [comment]
@marprok we can buffer the request on the server if the **page** is down, but not the other way around unfortunately.

**Comment by marprok** [comment]
@rexim That will do too. I mean the probability of the server to go offline is low anyways.

**Comment by rexim** [comment]
@marprok let's keep this issue for the server buffering. And for the chatbot buffering I created https://github.com/tsoding/HyperNerd/issues/374

Let's have the buffering on all chains of the system just in case. :+1:

**Comment by rexim** [comment]
Wiggle requests are not such an important thing to buffer them. If we lost one we lost one. No big deal.
